DROP TABLE IF EXISTS T_POST;
CREATE TABLE T_POST (
  ID             BIGINT(20) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  USER_ID        BIGINT(20) UNSIGNED NOT NULL,
  USER_NAME      VARCHAR(100),
  USER_IP        VARCHAR(100),
  POST_TITLE     TEXT        NOT NULL,
  POST_CONTENT   LONGTEXT    NOT NULL,
  STATUS         VARCHAR(20) NOT NULL,
  CREATE_AT      TIMESTAMP   NOT NULL,
  UPDATE_AT      TIMESTAMP   NOT NULL
)
DEFAULT CHARSET =UTF8;

CREATE INDEX IDX_POST ON T_POST (USER_ID, CREATE_AT);
