DROP TABLE IF EXISTS T_POST;
CREATE TABLE T_POST (
  POST_ID        BIGINT(20) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  POST_USER_ID   BIGINT(20) UNSIGNED NOT NULL,
  POST_USER_NICK VARCHAR(100),
  POST_USER_IP   VARCHAR(100),
  POST_DATE      TIMESTAMP  NOT NULL,
  POST_MODIFIED  TIMESTAMP,
  POST_CONTENT   LONGTEXT,
  POST_TITLE     TEXT    NOT NULL,
  POST_EXCERPT   TEXT,
  POST_STATUS    VARCHAR(20),
  COMMENT_STATUS VARCHAR(20),
  CREATED_AT     TIMESTAMP       NOT NULL,
  CREATED_BY     VARCHAR(20)     NOT NULL,
  UPDATED_AT     TIMESTAMP       NOT NULL,
  UPDATED_BY     VARCHAR(20)     NOT NULL
)
DEFAULT CHARSET =UTF8;

CREATE INDEX IDX_POST ON T_POST (POST_USER_ID, POST_DATE);
