DROP TABLE IF EXISTS T_POST;
CREATE TABLE T_POST (
  ID             BIGINT(20) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  USER_ID        BIGINT(20) UNSIGNED NOT NULL,
  USER_NAME      VARCHAR(100),
  USER_IP        VARCHAR(100),
  USER_AGENT     VARCHAR(255),
  MIME_TYPE      VARCHAR(20),
  TYPE           VARCHAR(20),
  TITLE          TEXT        NOT NULL,
  EXCERPT        TEXT,
  CONTENT        LONGTEXT    NOT NULL,
  STATUS         VARCHAR(20) NOT NULL,
  COMMENT_STATUS VARCHAR(20) NOT NULL,
  COMMENT_CNT    BIGINT(20) UNSIGNED NOT NULL,
  CREATED_AT     TIMESTAMP   NOT NULL,
  CREATED_BY     VARCHAR(20) NOT NULL,
  UPDATED_AT     TIMESTAMP   NOT NULL,
  UPDATED_BY     VARCHAR(20) NOT NULL
)
DEFAULT CHARSET =UTF8;

CREATE INDEX IDX_POST ON T_POST (USER_ID, CREATED_AT);
