DROP TABLE IF EXISTS T_LINK;
CREATE TABLE T_LINK (
  ID             BIGINT(20) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  USER_ID        BIGINT(20) UNSIGNED,
  POST_ID        BIGINT(20) UNSIGNED,
  LINK_URL       VARCHAR(255),
  LINK_NAME      VARCHAR(255),
  LINK_IMAGE     VARCHAR(255),
  LINK_TARGET    VARCHAR(25),
  LINK_REMARK    VARCHAR(255),
  LINK_VISIBLE   VARCHAR(20),
  LINK_RATING    INT(11),
  CREATED_AT     TIMESTAMP   NOT NULL,
  CREATED_BY     VARCHAR(20) NOT NULL,
  UPDATED_AT     TIMESTAMP   NOT NULL,
  UPDATED_BY     VARCHAR(20) NOT NULL
)
DEFAULT CHARSET =UTF8;

CREATE INDEX IDX_LINK ON T_LINK (USER_ID, POST_ID);
