DROP TABLE IF EXISTS T_TAG;
CREATE TABLE T_TAG (
  TAG_ID      BIGINT(20) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TAG_NAME    VARCHAR(100),
  TAG_DESC    TEXT    NOT NULL,
  CREATED_AT  TIMESTAMP       NOT NULL,
  CREATED_BY  VARCHAR(20)     NOT NULL,
  UPDATED_AT  TIMESTAMP       NOT NULL,
  UPDATED_BY  VARCHAR(20)     NOT NULL
)
DEFAULT CHARSET =UTF8;

CREATE UNIQUE INDEX IDX_TAG ON T_TAG (NAME);
