DROP TABLE IF EXISTS T_TERM;
CREATE TABLE T_TERM (
  ID          BIGINT(20) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR(200),
  REMARK      TEXT    NOT NULL,
  CREATED_AT  TIMESTAMP       NOT NULL,
  CREATED_BY  VARCHAR(20)     NOT NULL,
  UPDATED_AT  TIMESTAMP       NOT NULL,
  UPDATED_BY  VARCHAR(20)     NOT NULL
)
DEFAULT CHARSET =UTF8;

CREATE UNIQUE INDEX IDX_TERM ON T_TERM (NAME);
