DROP TABLE IF EXISTS T_COMMENT;
CREATE TABLE T_COMMENT (
  COMMENT_ID             BIGINT(20) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  COMMENT_USER_ID    BIGINT(20) UNSIGNED,
  COMMENT_USER_NICK  VARCHAR(100),
  COMMENT_USER_EMAIL VARCHAR(100),
  COMMENT_USER_URL   VARCHAR(200),
  COMMENT_USER_IP    VARCHAR(100),
  COMMENT_POST_ID    BIGINT(20) UNSIGNED NOT NULL,
  COMMENT_DATE       TIMESTAMP  NOT NULL,
  COMMENT_CONTENT    TEXT,
  COMMENT_APPROVED   VARCHAR(20),
  COMMENT_AGENT      VARCHAR(255),
  CREATED_AT     TIMESTAMP       NOT NULL,
  CREATED_BY     VARCHAR(20)     NOT NULL,
  UPDATED_AT     TIMESTAMP       NOT NULL,
  UPDATED_BY     VARCHAR(20)     NOT NULL
)
DEFAULT CHARSET =UTF8;

CREATE INDEX IDX_COMMENT_U ON T_COMMENT (COMMENT_USER_ID);
CREATE INDEX IDX_COMMENT_P ON T_COMMENT (COMMENT_POST_ID);
