DROP TABLE IF EXISTS T_TERM_TAXONOMY;
CREATE TABLE T_TERM_TAXONOMY (
  ID             BIGINT(20) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TERM_ID        BIGINT(20),
  TAXONOMY       VARCHAR(32),
  REMARK         TEXT,
  PARENT_ID      BIGINT(20) UNSIGNED,
  COUNT          BIGINT(20),
  CREATED_AT     TIMESTAMP       NOT NULL,
  CREATED_BY     VARCHAR(20)     NOT NULL,
  UPDATED_AT     TIMESTAMP       NOT NULL,
  UPDATED_BY     VARCHAR(20)     NOT NULL
)
DEFAULT CHARSET =UTF8;

CREATE UNIQUE INDEX UK_TERM_TAXONOMY ON T_TERM_TAXONOMY (TERM_ID, TAXONOMY);
CREATE INDEX IDX_TERM_TAXONOMY ON T_TERM_TAXONOMY (TAXONOMY);
