DROP TABLE IF EXISTS T_COMMENT;
CREATE TABLE T_COMMENT (
  ID             BIGINT(20) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  POST_ID        BIGINT(20) UNSIGNED NOT NULL,
  USER_ID        BIGINT(20) UNSIGNED NOT NULL,
  USER_NAME      VARCHAR(100),
  USER_EMAIL     VARCHAR(200),
  USER_URL       VARCHAR(200),
  USER_IP        VARCHAR(100),
  USER_AGENT     VARCHAR(255),
  TYPE           VARCHAR(20),
  CONTENT        TEXT,
  STATUS         VARCHAR(20)     NOT NULL,
  PARENT_ID      BIGINT(20) UNSIGNED,
  CREATED_AT     TIMESTAMP       NOT NULL,
  CREATED_BY     VARCHAR(20)     NOT NULL,
  UPDATED_AT     TIMESTAMP       NOT NULL,
  UPDATED_BY     VARCHAR(20)     NOT NULL
)
DEFAULT CHARSET =UTF8;

CREATE INDEX IDX_COMMENT_U ON T_COMMENT (USER_ID, CREATED_AT);
CREATE INDEX IDX_COMMENT_P ON T_COMMENT (POST_ID, CREATED_AT);
